---
- name: Update hostname
  become: yes
  command: hostnamectl set-hostname viacheslav-tsaruk-lab2

- name: Update /etc/hostname
  become: yes
  copy:
    content: "viacheslav-tsaruk-lab2\n"
    dest: /etc/hostname

- name: Update /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: "127.0.1.1 viacheslav-tsaruk-lab2"
    state: present
